### ISSUE TITLE
Date Range (Freshness)

### ISSUE THREAD

**Issue by mjunker** [YassKhazzan/openperplex_backend_os#14]
Hey

Thanks for creating OpenPerplex and sharing it with us!

It would be great if there was a way to pass the Google Serper Date Range parameter.

e.g. only search for past year, month, etc:
  "tbs": "qdr:y"
  "tbs": "qdr:m"
  ...

Same as in the Serper Playground: https://serper.dev/playground

Thanks

**Comment by YassKhazzan** [comment]
Hello,

Thank you for your support! We already have that feature in our roadmap, and we'll be releasing a new version of the API next week. Stay tuned!

**Comment by mjunker** [comment]
Awseome thanks!

**Comment by robcaulk** [comment]
@mjunker I noticed that Serper.dev limits you to controlling the time back in a very coarse manner. If you need higher resolution of time-range, I would recommend integrating the AskNews API, where you can control exact start and stop timestamps for your search: https://docs.asknews.app/en/reference#get-/v1/news/search. You also would avoid needing to scrape the links if you use the AskNews API, since it returns all the context necessary for an LLM to extract insights.

If you think it might be useful, I am happy to push a PR with it. 

Disclaimer: I am a developer of AskNews.

**Comment by mjunker** [comment]
Sounds interesting, this only supports news right? I'm interested in different media types.

@YassKhazzan is there an update if you plan to integrate the serper freshness?

**Comment by YassKhazzan** [comment]
already done in local env, will release this version by the end of this week

**Comment by YassKhazzan** [comment]
The latest version of the OpenPerplex API (v0.2.1) now includes a `recency_filter` feature. You can find the documentation here: https://pypi.org/project/openperplex/. The full documentation at [docs.openperplex.com](https://docs.openperplex.com/) will be updated tomorrow.

**Comment by mjunker** [comment]
Thanks! I noticed the latest version does not return a date field anymore? This was a nice feature which was useful for me.

**Comment by YassKhazzan** [comment]
in the sources ? okay i will fix that

**Comment by mjunker** [comment]
yes, awesome thanks!
